const List<Map<String, dynamic>> rooms = [
  {
    'room_id': 1,
    'room_code': '1',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 2,
    'room_code': '2',
    'name': 'Tecnología 1 - Aula',
    'course': null,
    'capacity': 25,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 3,
    'room_code': '4',
    'name': 'Almacén central',
    'course': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 4,
    'room_code': '5',
    'name': 'Limpieza',
    'course': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 5,
    'room_code': '6',
    'name': 'Archivo',
    'course': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 6,
    'room_code': '7',
    'name': 'Visitas',
    'course': null,
    'capacity': 8,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 7,
    'room_code': '8',
    'name': 'Dirección',
    'course': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 8,
    'room_code': '9',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 9,
    'room_code': '10',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 10,
    'room_code': '11',
    'name': 'Almacén secretaría',
    'course': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 11,
    'room_code': '12',   
    'name': 'Biblioteca',
    'course': null,
    'capacity': 15,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 12,
    'room_code': '13',
    'name': 'Tecnología 2 - Aula',
    'course': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 13,
    'room_code': '15',
    'name': 'Administración',
    'course': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 14,
    'room_code': '16',
    'name': 'Jefes de Estudios',
    'course': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 15,
    'room_code': '17',
    'name': 'FCT',
    'course': null,
    'capacity': 7,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 16,
    'room_code': '18',
    'name': 'Almacén',
    'course': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 17,
    'room_code': '19',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 18,
    'room_code': '20',
    'name': 'Gimnasio',
    'course': null,
    'capacity': 50,
    'building': 1,
    'floor': 1,
  },
  {
    'room_id': 19,
    'room_code': '20A',
    'name': 'Vestuario2',
    'course': null,
    'capacity': 15,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 20,
    'room_code': '21',
    'name': 'Vestuario1',
    'course': null,
    'capacity': 15,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 21,
    'room_code': '22',
    'name': 'Materiales',
    'course': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 22,
    'room_code': '23',
    'name': 'D1',
    'course': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 23,
    'room_code': '24',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 24,
    'room_code': '25',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 25,
    'room_code': '26',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 26,
    'room_code': '27',
    'name': 'DESDBL - OT',
    'course': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 27,
    'room_code': '30',
    'name': 'Conserjería',
    'course': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 28,
    'room_code': '31',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 29,
    'room_code': '32',
    'name': 'OT.B',
    'course': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 30,
    'room_code': '33',
    'name': 'OT.A',
    'course': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 31,
    'room_code': '34',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 32,
    'room_code': '35',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 33,
    'room_code': '35A',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 34,
    'room_code': '36',
    'name': 'Música 1 - Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 35,
    'room_code': '37',
    'name': 'Aula',
    'course': null,
    'capacity': 15,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 36,
    'room_code': '38',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 37,
    'room_code': '39',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 38,
    'room_code': '40',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 39,
    'room_code': '44',
    'name': 'Almacén',
    'course': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 40,
    'room_code': '45',
    'name': 'Cafetería',
    'course': null,
    'capacity': 50,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 41,
    'room_code': '46',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 42,
    'room_code': '47',
    'name': 'Aula',
    'course': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 43,
    'room_code': '48',
    'name': 'Música 2 - Lenguaje Musical - Aula',
    'course': null,
    'capacity': 15,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 44,
    'room_code': '49',
    'name': 'Música - D2 Piano - Aula',
    'course': null,
    'capacity': 7,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 45,
    'room_code': '50',
    'name': 'Música - D3 - Aula',
    'course': null,
    'capacity': 7,
    'building': 2,
    'floor': 1,
  },
  {
    'room_id': 46,
    'room_code': '51',
    'name': 'Música - D4 - Aula',
    'course': null,
    'capacity': 7,
    'building': 2,
    'floor': 1,
  },
];