const List<Map<String, dynamic>> rooms = [
  {
    'roomId': 1,
    'roomCode': '1',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 2,
    'roomCode': '2',
    'name': 'Tecnología 1 - Aula',
    'courseName': null,
    'capacity': 25,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 3,
    'roomCode': '4',
    'name': 'Almacén central',
    'courseName': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 4,
    'roomCode': '5',
    'name': 'Limpieza',
    'courseName': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 5,
    'roomCode': '6',
    'name': 'Archivo',
    'courseName': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 6,
    'roomCode': '7',
    'name': 'Visitas',
    'courseName': null,
    'capacity': 8,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 7,
    'roomCode': '8',
    'name': 'Dirección',
    'courseName': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 8,
    'roomCode': '9',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 9,
    'roomCode': '10',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 10,
    'roomCode': '11',
    'name': 'Almacén secretaría',
    'courseName': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 11,
    'roomCode': '12',   
    'name': 'Biblioteca',
    'courseName': null,
    'capacity': 15,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 12,
    'roomCode': '13',
    'name': 'Tecnología 2 - Aula',
    'courseName': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 13,
    'roomCode': '15',
    'name': 'Administración',
    'courseName': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 14,
    'roomCode': '16',
    'name': 'Jefes de Estudios',
    'courseName': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 15,
    'roomCode': '17',
    'name': 'FCT',
    'courseName': null,
    'capacity': 7,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 16,
    'roomCode': '18',
    'name': 'Almacén',
    'courseName': null,
    'capacity': 0,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 17,
    'roomCode': '19',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 18,
    'roomCode': '20',
    'name': 'Gimnasio',
    'courseName': null,
    'capacity': 50,
    'building': 1,
    'floor': 1,
  },
  {
    'roomId': 19,
    'roomCode': '20A',
    'name': 'Vestuario2',
    'courseName': null,
    'capacity': 15,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 20,
    'roomCode': '21',
    'name': 'Vestuario1',
    'courseName': null,
    'capacity': 15,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 21,
    'roomCode': '22',
    'name': 'Materiales',
    'courseName': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 22,
    'roomCode': '23',
    'name': 'D1',
    'courseName': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 23,
    'roomCode': '24',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 24,
    'roomCode': '25',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 25,
    'roomCode': '26',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 26,
    'roomCode': '27',
    'name': 'DESDBL - OT',
    'courseName': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 27,
    'roomCode': '30',
    'name': 'Conserjería',
    'courseName': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 28,
    'roomCode': '31',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 29,
    'roomCode': '32',
    'name': 'OT.B',
    'courseName': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 30,
    'roomCode': '33',
    'name': 'OT.A',
    'courseName': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 31,
    'roomCode': '34',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 32,
    'roomCode': '35',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 33,
    'roomCode': '35A',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 34,
    'roomCode': '36',
    'name': 'Música 1 - Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 35,
    'roomCode': '37',
    'name': 'Aula',
    'courseName': null,
    'capacity': 15,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 36,
    'roomCode': '38',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 37,
    'roomCode': '39',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 38,
    'roomCode': '40',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 39,
    'roomCode': '44',
    'name': 'Almacén',
    'courseName': null,
    'capacity': 0,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 40,
    'roomCode': '45',
    'name': 'Cafetería',
    'courseName': null,
    'capacity': 50,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 41,
    'roomCode': '46',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 42,
    'roomCode': '47',
    'name': 'Aula',
    'courseName': null,
    'capacity': 20,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 43,
    'roomCode': '48',
    'name': 'Música 2 - Lenguaje Musical - Aula',
    'courseName': null,
    'capacity': 15,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 44,
    'roomCode': '49',
    'name': 'Música - D2 Piano - Aula',
    'courseName': null,
    'capacity': 7,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 45,
    'roomCode': '50',
    'name': 'Música - D3 - Aula',
    'courseName': null,
    'capacity': 7,
    'building': 2,
    'floor': 1,
  },
  {
    'roomId': 46,
    'roomCode': '51',
    'name': 'Música - D4 - Aula',
    'courseName': null,
    'capacity': 7,
    'building': 2,
    'floor': 1,
  }
];