const List<Map<String, dynamic>> users = [
  {
    'user_id': '1a1fcf19-6cbc-4d30-be9f-59f337c633a5',
    'name': 'Clara',
    'last_name': 'Montagut Peña',
    'email': 'claramontagut@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 2, 'name': 'teacher' },
    'department': { 'department_id': 7, 'name': 'Informática' },
  },
  {
    'user_id': '2b2fdf27-7aad-4b91-bb3d-20e9b8c773d1',
    'name': 'Javier',
    'last_name': 'Ruiz Navarro',
    'email': 'javierruiz@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 2, 'name': 'teacher' },
    'department': { 'department_id': 17, 'name': 'Matemáticas' },
  },
  {
    'user_id': '3c3eed38-5cbc-412d-bb21-7d8923f664b2',
    'name': 'María',
    'last_name': 'Gómez Torres',
    'email': 'mariagomez@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 2, 'name': 'teacher' },
    'department': { 'department_id': 7, 'name': 'Informática' },
  },
  {
    'user_id': '4d4adc49-9aef-45aa-aab4-61fa1020a9f3',
    'name': 'Carlos',
    'last_name': 'Domínguez Pérez',
    'email': 'carlosdominguez@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 3, 'name': 'janitor' },
    'department': null,
  },
  {
    'user_id': '5e5bcb50-2eab-4c09-bf47-b3a9c2e5de14',
    'name': 'Lucía',
    'last_name': 'Santos Molina',
    'email': 'luciasantos@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 2, 'name': 'teacher' },
    'department': { 'department_id': 13, 'name': 'Inglés' },
  },
  {
    'user_id': '6f6dad61-1bba-41b8-bb62-7a8b5ed9cfe5',
    'name': 'Álvaro',
    'last_name': 'Núñez López',
    'email': 'alvaronunez@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 1, 'name': 'admin' },
    'department': { 'department_id': 2, 'name': 'Biología y Geología' },
  },
  {
    'user_id': '7g7ede72-3ddc-44d0-bc9b-8e6b6f8e7df6',
    'name': 'Beatriz',
    'last_name': 'Ortega Sáez',
    'email': 'beatrizortega@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 4, 'name': 'support_staff' },
    'department': null,
  },
  {
    'user_id': '8h8acf83-9cce-4e2a-bd25-c5a3e9c1a8d7',
    'name': 'Raúl',
    'last_name': 'Martínez Rico',
    'email': 'raulmartinez@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 2, 'name': 'teacher' },
    'department': { 'department_id': 15, 'name': 'Castellano' },
  },
  {
    'user_id': '9i9bdf94-5fdd-46a5-bc71-1e9b1a9b9f08',
    'name': 'Patricia',
    'last_name': 'León Ramos',
    'email': 'patricialeon@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 4, 'name': 'support_staff' },
    'department': null,
  },
  {
    'user_id': '10j10ef05-8aee-4bcb-bb87-5e8a3e0b3f29',
    'name': 'Miguel',
    'last_name': 'Fernández Alba',
    'email': 'miguelfernandez@edu.gva.es',
    'user_img': 'avatar_1.webp',
    'role': { 'role_id': 1, 'name': 'admin' },
    'department': { 'department_id': 9, 'name': 'Física y Química' },
  },
];